### ISSUE TITLE
Add Sn1per to recon tools list

### ISSUE THREAD

**Issue by 1N3** [infosecn1nja/Red-Teaming-Toolkit#18]
Can you add Sn1per to the "Frameworks" section (https://github.com/1N3/Sn1per)? It does both active/passive recon/OSINT collection automatically.

**Comment by infosecn1nja** [comment]
Done added Sn1per! https://github.com/infosecn1nja/Red-Teaming-Toolkit/commit/023a3c7e9f4fd5dd24d2424cbc946e51c1bbeeac

**Comment by 1N3** [comment]
Thanks man!
